[package]
name = "streamsync"
version = "0.1.0"
authors = ["serxka <serxka@protonmail.com>"]
edition = "2018"

[dependencies]
actix = "0.10"
actix-files = "0.3"
actix-web = "3"
actix-web-actors = "3"

rand = "0.8"
serde = "1.0"
serde_json = "1.0"
